#general

SECRET_KEY = 'Password'
RECAPTCHA_PUBLIC_KEY = '6Lde174UAAAAALrvXJzVdpkj_y2NnGbma2FSfMFa'
RECAPTCHA_PRIVATE_KEY = '6Lde174UAAAAAJI2fS0UySX-20jwnAhwouh6BSEG'
Testing = True

#db
SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:site.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

